#
# devcrate
# azure pipelines CI
#

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  registry: docker.io
  version: latest
  tag_user: mrzzy
  # docker image names
  base_image: "$(registry)/$(tag_user)/devcrate"
  cloud_image: "$(registry)/$(tag_user)/devcrate-cloud"
  
trigger:
- master
- develop

stages:
- stage: build
  jobs:
    # build devcrate
    - job: build_base_image
      steps:
      - script: |
          make $(base_image)
          make save/$(base_image)
      - publish: devcrate.tar
        artifact: base_image
    # devcrate cloud 
    - job: build_cloud_image
      dependsOn: build_base_image
      steps:
      - download: current
        artifact: base_image
      - script: |
          env COMMIT_PATH="$(Pipeline.Workspace)/base_image" make load/$(base_image)
          make $(cloud_image)
          make save/$(cloud_image)
      - publish: devcrate-cloud.tar
        artifact: cloud_image
      
- stage: deploy
  dependsOn: build
  jobs:
    # push devcrate
    - job: deploy_base_image
      steps:
      - download: current
        artifact: base_image
      - script: |
          env COMMIT_PATH="$(Pipeline.Workspace)/base_image" make load/$(base_image)
      - task: Docker@2
        inputs:
          containerRegistry: dockerhub-mrzzy
          repository: "mrzzy/devcrate"
          command: push
          tags: $(version)

    # push devcrate-cloud
    - job: deploy_cloud_image
      steps:
      - download: current
        artifact: cloud_image
      - script: |
          env COMMIT_PATH="$(Pipeline.Workspace)/cloud_image" make load/$(cloud_image)
      - task: Docker@2
        inputs:
          containerRegistry: dockerhub-mrzzy
          repository: "mrzzy/devcrate-cloud"
          command: push
          tags: $(version)
