#
# Devcrate
# zshrc
# ZSH Configuration file
#

# History configuration
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="dd/mm/yyyy"
HISTSIZE=100000
SAVEHIST=100000
setopt share_history
setopt inc_append_history
