
# zshrc
# ZSH Configuration file
#

#Paths
export GOPATH="$HOME/go"
export PATH="/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

#Locale
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Program settings
export SHELL=zsh
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
    export VISUAL="vim"
else
    export EDITOR='nvim'
    export VISUAL="nvim"
fi

# Aliases
alias ls='ls -F --color=none'
alias vim="nvim"
alias v="nvim"
alias py="python3"
alias rb="ruby"
alias g="git"
alias tmux="tmux new-session -A -s $HOST"
alias t="tmux"
alias less="less -R"

# Compilation flags
export ARCHFLAGS="-arch x86_64"

#Plugin Configuration
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="dd/mm/yyyy"
HISTSIZE=100000
SAVEHIST=100000
setopt share_history
setopt inc_append_history

#zplug
## NOTE: </dev/null is a hack to get zplug to work in docker build
source ~/.zplug/init.zsh
zplug "plugins/vi-mode", from:oh-my-zsh </dev/null
zplug "plugins/git-fast", from:oh-my-zsh </dev/null
zplug "mafredri/zsh-async" </dev/null
zplug "miekg/lean", as:theme, use:"lean.plugin.zsh" </dev/null

ZSH_TMUX_AUTOSTART=true

# Lean Prompt
PROMPT_LEAN_TMUX=">"
PROMPT_LEAN_VIMODE="1"
PROMPT_LEAN_NOTITLE="1"
PROMPT_LEAN_NOTITLE="1"
PROMPT_LEAN_COLOR1="244"
PROMPT_LEAN_COLOR2="208"
PROMPT_LEAN_COLOR3="244"
PROMPT_LEAN_ABBR_METHOD="shrink"

zplug load #Load Plugins

# Z directory jumping tool
source "$HOME/.local/share/z.sh"

# Lazy Load Implmentation
# Usage: lazy_load(load_cmd, activator, activators... __EOA__ args_activator
# Runs the lazy load command, dealiases all activators and executes the
# activator with the given command line arguments
lazy_load()
{
    load_cmd="$1";shift
    activator="$2";shift

    # Unalias activator aliases since the lazy is about to be run
    local PARSED_ACTIVATORS=false # Whether activators have been parsed
    local ACTIVATOR_ARGS="" 
    for arg in $*
    do
        if [ $arg = "__EOA__" ]
        then 
            local PARSED_ACTIVATORS=true
        else
            if $PARSED_ACTIVATORS
            then 
                # Collect command line arguments for activator command
                ACTIVATOR_ARGS="$ACTIVATOR_ARGS $arg"
            else
                # Remove activator aliases since load command has already run
                unalias "$arg"
            fi
        fi
    done

    # Run Lazy load command
    eval " $load_cmd"

    # Run activator with collected command line args
    eval " $activator $ACTIVATOR_ARGS"
}

# Usage: lazy(load_cmd, activators...)
# Mitigates the unnecessary overhead of the the 'load_cmd' on startup, only
# runs the load command if the user touches any of the 'activators' aliases,
# then which the lazy loader actually loads the load command.
# activators is a space seperated string of activation alias that will cause
# the load command to run, thereafter activator command will run.
# 
lazy()
{
    load_cmd="$1"
    shift
    for activator in $*
    do
        # printf required because load command can contain spaces
        # __EOA__ is used to enote end of activators and start of command line arguments for the activators
        load_alias="`printf 'lazy_load "%s" %s %s "__EOA__" \n' "$load_cmd" "$activator" "$*"`"
        alias "$activator"="$load_alias"
    done 
}

# lazy load conda
lazy "source /opt/conda/etc/profile.d/conda.sh" conda
