#
# devcrate
# Github Actions CI
# Build Workflow
#

# workflow to build docker images on pull request
on:
  pull_request: {}

env:
  # use docker buildkit to speed up builds
  DOCKER_BUILDKIT: 1
  REPOSITORY: docker.io
  DOCKER_USER: mrzzy
  
jobs:
  build-push-images:
    name: Build & Push Docker images
    strategy:
      matrix:
        variant:
          - ""
          - "cloud"
    runs-on: ubuntu-20.04
    steps:
    - name: Build devcrate-${{matrix.variant}}
      run: |
        apt-get update && apt-get install make --no-install-recommends
        make ${REPOSITORY}/${DOCKER_USER}/devcrate-${{matrix.variant}}
